### ISSUE TITLE
Wildcard support

### ISSUE THREAD

**Issue by zzzare** [aloopkin/WinCertes#1]
I saw in README that there is a support for wildcard SSL.

My command looked like this:
wincertes.exe -e myemail@gmail.com -d *.mydomain.com 

I wanted to get a wildcard certificate and I get the error:
"Failed to register and validate order with CA: Only HTTP challenges are supported for now"

Am I doing something wrong?
Thank you!

**Comment by aloopkin** [comment]
I found a nasty bug in wildcard certificate handling, probably due to a line lost in code refactoring at some point. So now the code is 100% working.
However, the mentioned bug is not where you get this error from... so i don't know what's happening in your case. Could you try to debug a bit more?

**Comment by aloopkin** [comment]
Ok, i got it: Let's Encrypt does not allow http-01 validation method for wildcard certificates. So, it simply won't work...
