### ISSUE TITLE
Error Could not delete challenge file directory

### ISSUE THREAD

**Issue by anibal-acosta** [aloopkin/WinCertes#11]
I need to set a web.config in the .well-known directory to avoid forms authentication redirect.
So, I need to keep this directory. 

When WinCertes finish, try to cleanup those directories and got error because this is not empty

Maybe the solution is to delete only directories that WinCertes effective created in the process and not those already exists

**Comment by aloopkin** [comment]
makes sense, and btw, there could be other programs that write to the well-known directory, for other reasons than ACME support.
see commit [#b3a488f3f116621280594682ceada179823acd29](https://github.com/aloopkin/WinCertes/commit/b3a488f3f116621280594682ceada179823acd29)

**Comment by anibal-acosta** [comment]
In my case, the whole site is protected with asp.net forms authentication. So and cannot exclude well-known directory because has a dot ".well-known" in the beginning. So the solution was convert the ".well-known" to IIS application and add the web.config in root to allow anonymous access.

**Comment by aloopkin** [comment]
Can you please test this for both bugs.
[WinCertes-Debug.1.1.0.100.msi.zip](https://github.com/aloopkin/WinCertes/files/2822006/WinCertes-Debug.1.1.0.100.msi.zip)

**Comment by anibal-acosta** [comment]
I download the source from github and for some reason this doesnt work, the
console just show:

[DEBUG] PFX password will be: 6f832f86286141c3
[DEBUG] Current certificate expiration date is:
And then terminate.

I ran the previous version and the process completes with success

**Comment by aloopkin** [comment]
In this beta version, either -w (use existing web server) or -a (spawn built-in web server) must be configured

**Comment by aloopkin** [comment]
fixed in version 1.1.1
