### ISSUE TITLE
Allow private keys to be exportable

### ISSUE THREAD

**Issue by Adambean** [aloopkin/WinCertes#13]
Could we have an option to allow private keys to be exportable from the certificate store?

This is required to make the certificate and key available to other software that needs them in PEM formats, such as Apache and hMailServer. What I'd typically export in PEM format:

* Private key, "<subject>.key"
* End entity certificate, "<subject>.crt"
* Full certificate chain, "<subject>.pem"

I did look into the PowerShell script option but that only runs if a certificate is really issued on that run. (You can't run it again for already issued certificates until they're renewed.) There also seems to be absolutely no documentation around the object structure returned by ``Get-PfxData`. (Microsoft's docs are next to useless on this.)

An alternative could be to have an option in WinCertes save a PFX (or PKCS#12) file to a specified location instead of needing to go through PowerShell. I could then give that file to OpenSSL for the PEM file generation.

**Comment by aloopkin** [comment]
Please see issue #9

**Comment by Adambean** [comment]
What a star! Looks like a hefty job to get this working in PowerShell, but the answer is definitely there.
