### ISSUE TITLE
Certificate name (visual name) conflict

### ISSUE THREAD

**Issue by anibal-acosta** [aloopkin/WinCertes#14]
I need to add a seconds host to my IIS. For example, the First is: www.mydomain.com
and the new is www.myotherdomain.com

I realize that wincertes creates a certificate and store it using just the first part of the domain, in this case will be "www" for both.

In the Binding window of the IIS Manager, the UI only show the Certificate Name (not the "issue to" information).

So, I thinks that could be a good practice to save the certificate not only using the first part of the domain but the complete domain name, and include the expiration date.

For example: Instead of "www", save as: "www.mydomain.com_exp2019-06-18"

**Comment by aloopkin** [comment]
Unfortunately, the way this name is handled, i can't do it that way.
Nevertheless, i tried to improved it, the code is commited and pushed. Can you please check?
