### ISSUE TITLE
Certificate validation fails

### ISSUE THREAD

**Issue by PHCCorso** [aloopkin/WinCertes#15]
When running WinCertes, it gives me the following output:

    Generated orders and validated challenges for domains: www.mywebsite.com
    Failed to retrieve certificate from CA: Failed to read certificate - version 1 certificate contains extra data

I've searched about the problem and the only thing I've found about it [was this](https://github.com/bcgit/bc-csharp/issues/158):

> The issue is that the (absent because == default) version indicates a V1 certificate, but there are extensions present (the "extra data") in the ASN.1 sequence, which is a feature added for V3. Given that the purported issuer is "My CA V3" I would guess the certificate creator was trying to create a V3 CA cert, but the version was not set correctly.

But I don't know how to solve the problem.  Any help?

**Comment by aloopkin** [comment]
Is this bug still happening? Do you get it when enrolling on Let's Encrypt, or another CA?

**Comment by PHCCorso** [comment]
@aloopkin Sorry, I didn't keep looking into it. Instead, I've moved to [WACS](https://github.com/PKISharp/win-acme).

> Do you get it when enrolling on Let's Encrypt, or another CA?

I've only tried it with Let's Encrypt.
