### ISSUE TITLE
No token created

### ISSUE THREAD

**Issue by Datarmanatar** [aloopkin/WinCertes#17]
When I do the following:
C:\Users\administrator.VOXIT>WinCertes.exe -e roland.ohlsson@mypage.se -d ablemonitor.com -w -b "MyPageName" -p
Nothing gets created in ".well-known\acme-challenge" map that the "MyPageName" is reffering to.
I also tested with -w "C:\inetpub\mypage" and with -w "C:\inetpub" with no success.

**Comment by aloopkin** [comment]
Hello,

It's difficult to answer, not knowing your IIS configuration:

- the path after "-w" should refer to IIS' website root (the one you get when you access http://localhost/)
- the name after "-b" refers to the website name in the IIS Management Console. The default is "Default Web Site"

**Comment by SergeMalkin** [comment]
Hello,
I have the same problem. Key -w does not work. For test, I used -w "C:\test" parameter, but folder \.well-known is still created in "C:\inetpub\wwwroot\.well-know".

**Comment by aloopkin** [comment]
sorry, forgot to answer on that one: the correct syntax is -w=c:\test
hence the issues you got.

**Comment by aloopkin** [comment]
Usage documentation released along with WinCertes 1.4.0
