### ISSUE TITLE
Only binds certificate to the first HTTPS hostname

### ISSUE THREAD

**Issue by pgordinho** [aloopkin/WinCertes#23]
When having  multiple HTTPS bindings only one receives the certificate. It's a common practice to have multiple bindings like xxx.com and www.xxx.com but only one gets updated

**Comment by aloopkin** [comment]
Will fix that in next version.

Would you be interested in testing beta version before release ?

**Comment by pgordinho** [comment]
Sure, I’ll be glad to help. WinCerts is totally what I need. Great work
Just send the beta version when it’s ready and I’ll test

**Comment by aloopkin** [comment]
Could you please try the beta from there:
https://mail.nikosoft.net/mft/effc60f8bb97

**Comment by pgordinho** [comment]
Hi Alexandre

All seems to be fine.

It did renew all the bindings  and kept the “require server name indication flag”
Did test in multiple sites using

wincertes -e gordon@outlook.pt -d domain.pt -d www.domain.pt -b "www.domain.pt" -w=D:\ www.domain.pt<http://www.domain.pt>

All seems to be working as expected.

A possible future feature would be getting -d and -w parameters from IIS.

Another thing… Using -p parameter (very helpful) will create the task without the -e -b and -w parameters and would not work in this case. I think the schedule task should be created with the same parameters specified in the command line.

Great work!
Thanks!

**Comment by aloopkin** [comment]
Great news! What about the SNI flags, are they kept now on renewal?

Regarding the other flags, don't worry, they are saved. If you use --show you can see the details of the saved settings.

**Comment by pgordinho** [comment]
They are kept! That was the most important thing!
First thing I checked. It’s perfect!
