### ISSUE TITLE
Require Server name Indication gets unchecked 

### ISSUE THREAD

**Issue by pgordinho** [aloopkin/WinCertes#24]
When binding a certificate to a IIS website the "Require Server name Indication" checkbox in the HTTPS site bind gets unchecked and all the HTTPS sites get the same last binded certificates.

To fix this is necessary to go manually set them all again, which invalidates the auto renew option.

**Comment by aloopkin** [comment]
That one is more tricky: it's due to the using of the old MS IIS Administration DLL. Unfortunately, switching to a more recent one causes issues. Will try to solve it.

**Comment by pgordinho** [comment]
Hi

Tried the new version without success...
Got an error reading the registry


Warning: Could not open/create registry subkey: Requested registry access is not
 allowed.. We'll try to continue anyway.
Could not Read/Write command line parameters to configuration: Requested registr
y access is not allowed.
Warning: Could not open/create registry subkey: Requested registry access is not
 allowed.. We'll try to continue anyway.

Unhandled Exception: System.Security.SecurityException: Requested registry acces
s is not allowed.
   at System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   at Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   at WinCertes.RegistryConfig.DeleteAllParameters()
   at WinCertes.Program.Main(String[] args)


________________________________

**Comment by aloopkin** [comment]
Which command are you typing?
