### ISSUE TITLE
Registry Access

### ISSUE THREAD

**Issue by dcuschieri** [aloopkin/WinCertes#27]
I am trying the following command in a command prompt with elevated admin rights, after logging in as a local admin:

`WinCertes.exe -e myemail@domain.com -d site.domain.com -w -b "My IIS Site Name" -p -t 7`

WinCertes is returning the error: "Requested registry access is not allowed"

What could the issue be?

**Comment by yannlec** [comment]
Same for me. I had to set the ACL in the registry HKLM:\SOFTWARE\WinCertes ... Bug ?

**Comment by josh-abram** [comment]
Same here.

**Comment by aloopkin** [comment]
Actually, i've tried to programmatically set the permissions on HKLM:\SOFTWARE\WinCertes. Unfortunately, it seems in some cases it prevents from actually using it.

So i've reverted that attempt. Will be released in next version.

**Comment by aloopkin** [comment]
Can you please test the following, and see if it fixes your issue ?
You may need to delete HKLM\Software\WinCertes manually, in case it doesn't work with the exe out of the box.
[WinCertes-Debug.1.4.0beta3.msi.zip](https://github.com/aloopkin/WinCertes/files/4677301/WinCertes-Debug.1.4.0beta3.msi.zip)

**Comment by yannlec** [comment]
it seems to work fine, thanks !

**Comment by aloopkin** [comment]
Fix released as part of WinCertes 1.4.0
