### ISSUE TITLE
CertesWrapper potential path code error

### ISSUE THREAD

**Issue by cshawky** [aloopkin/WinCertes#29]
Please check code in CertesWrapper.cs:
"System.IO.File.WriteAllBytes(pathForPfx + "\\" + pfxName, pfxBytes);"
pfxName already includes pathForPfx
Thanks

**Comment by aloopkin** [comment]
The code is actually:
System.IO.File.WriteAllBytes(pfxName, pfxBytes);
since commit c6f541c and including latest commit c5caf0d

**Comment by cshawky** [comment]
Thanks
My mistake, I did an offline compare on my PC and merged your recent changes. As a last check, I used the compare on github. I did not realise it would compare against base, that is how I picked this issue up. Already updates as you say.  
Now trying to work out how to compare your latest commit with mine...Any clues you can  provide would be appreciated.
https://stackoverflow.com/questions/31671585/github-comparing-across-forks

**Comment by cshawky** [comment]
I gave up with the comparison above and re forked the repository to check all diffs. I have re imported my HandleOptions mods into my fork after updating all code changes you did. I felt the need to keep the new class as a stepping stone to separate all registry interaction from the main certificate code.
Thanks for taking on my ideas. Still on my list to do those example scripts, I'm currently just running manually on my VPS.
