### ISSUE TITLE
"Object reference not set to an instance of an object." when using option --extra[=VALUE]

### ISSUE THREAD

**Issue by afantini-onit** [aloopkin/WinCertes#30]
Version 1.4.1 (installed with WinCertes-Debug.1.4.1.msi installer) returns "Object reference not set to an instance of an object." when using command line option --extra[=VALUE]

First try:
`WinCertes.exe -a -e me@example.com -d test1.example.com -d test2.example.com -p --extra=0`

Second try:
`WinCertes.exe -a -e me@example.com -d test1.example.com -d test2.example.com -p --extra=1`

![WinCertes_1 4 1_NullReferenceException](https://user-images.githubusercontent.com/58432994/93321481-7e487900-f812-11ea-9173-1eafe2508675.png)

I temporarily switched back to version 1.3.0 and managed to configure two certificates by using `--extra` option (without an integer index).

**Comment by valeriob** [comment]
Hi,
we got the same problem, here is a fix.
https://github.com/aloopkin/WinCertes/pull/31

**Comment by aloopkin** [comment]
Released as v1.4.2
