### ISSUE TITLE
About web server root option

### ISSUE THREAD

**Issue by zhangsir199** [aloopkin/WinCertes#33]
By the option description, web server root was indicated by `-w` option,
however It is Invalid if you using `-w mypath`, while `-w=mypath` is OK.

**Comment by aloopkin** [comment]
The help says:
  -w, --webserver[=ROOT]     toggles the local web server use and sets its ROOT
                               directory (default c:\inetpub\wwwroot).

it clearly states =ROOT (mypath in your example).

**Comment by zhangsir199** [comment]
I means the other options  can use space, such as `-e mail`,`-e=mail`,`-d domain`,`-d=domain`, these are all OK.
In your quick start command: `WinCertes.exe -e me@example.com -d test1.example.com -d test2.example.com -w -b "Default Web Site" -p`,  there is no equal sign, this mislead me and waste lot of time.
