### ISSUE TITLE
No EXE in the repo

### ISSUE THREAD

**Issue by 300cpilot** [aloopkin/WinCertes#5]
A lot of people are not up to speed on compiling. You might want to explain enough to get a noob going.

**Comment by brianedwards71** [comment]
Compile the software using Visual Studio to get the executable. Works fine.

**Comment by rvschaffer** [comment]
Please add a pre compiled version. It would make the life of those who don't use Visual Studio regularly much easier.

**Comment by aloopkin** [comment]
I don't understand: there is a pre-compiled version in https://github.com/aloopkin/WinCertes/releases

**Comment by 300cpilot** [comment]
The problem is that no where in the readme or the instructions start where the compiled version is. This is more of a request to include the more basic instructions needed to run your program. Many see this and expect the exe to be sitting right there for download. Your not the only one that does this. I just felt that your project could be helped by allowing users with no programming knowledge to use your software without having to learn programming or searching the repo.
Thanks,



________________________________

**Comment by ElimAdmin** [comment]
Thank you for your work on this @aloopkin.  Like others, it took me time to work out where to download the exe from: [https://github.com/aloopkin/WinCertes/releases].  You are an expert. We are trying to make our way, a long way behind you.  A simple link in the instructions for the noobs - that's all we ask.  :)  I don't think it's an issue of Github clarity - it's one of knowledge and understanding - and we're all trying to gain that.  Today I have found where 'Releases' can be found.  I'm moving forward.  Thank you again.
